src/elements/heading.jsx
src/elements/heading.md
src/elements/index.js
src/foundation/README.md
src/index.js
styleguide.config.js

Adds `Heading` component and a simple documentation about how CSS custom properties work with the typography.

Add headings documentation

---

src/foundation/type.css
styleguide.config.js

Adds `--font-family-base` to fix missing font face.
Removes redundant font-family duplication from styleguidist
configuration.

Fix font face based on custom property

---

.eslintrc.yml
src/elements/forms/text-field.jsx

If we use default props. All text fields will share the same ID. This PR should prevent it.

Fix generate unique ID for every text field

---

.github/workflows/publish-package.yml

Created event is not triggered when release draft is converted to published

Use published event for package release

---

src/elements/forms/text-field.css
src/elements/forms/text-field.jsx

For some browsers `:not(:placeholder-shown)` is not triggered hence this new rule

Move placeholder up when input is autofilled

---

src/elements/button/button.jsx

I decided that the implicit tag selecting based on the props is fine for the library even if it's not obvious.
It will only work when the user did not pass a tag explicitly, so it should not break any code. @Joozty what do you think?

Add auto link detection to Button

---

src/elements/forms/text-field.css
src/elements/forms/text-field.jsx
src/elements/forms/text-field.md

Introduces class-first approach for the inputs.
Fixes the bug with the Firefox broken label animation by removing the `-webkit-autofill` selector.
---
@Joozty I wanted to fix the bug and ended up rewriting everything. Even if it seems not worth it, it is for me. This may be the first step of writing the next forms API in the library. Let me know what do you think about.

Improve TextField API and styles

---

src/elements/forms/control.jsx
src/elements/forms/forms.md
src/elements/forms/index.css
src/elements/forms/styles.css
src/elements/forms/text-field.css

Adjusts TextField styles to be more flexible for the Select
and TextArea elements:
* adds line-height
* reduces vertical padding
* includes new variables to the calculations
Potential problems:
* `line-height` changes with the label during the sliding animation, what may lead to performance issues
Adds `FormControl` element as a wrapper around simple `input`, `textarea` and `select`. @Joozty do I miss any other element should be covered?

Develop form control

---

src/elements/forms/control.jsx
src/elements/forms/forms.md
src/elements/forms/index.js
src/elements/forms/label.jsx
src/elements/forms/styles.css

Adds a wrapper around the `<label>` element.
Copies styles from TextField partially. Slightly adjusts `%label` class font-size.
Adjusts example file adding imports and displaying 2 use cases of the label: before and after the input.

Add a FormLabel wrapper around <label>

---

src/elements/forms/styles.css

It's a dangerous thing that is required for the following steps in development but may **break** other product. Please, take a look at the comment in the file.

Add flex layout to the FormGroup

---

bin/config.js
package-lock.json
package.json
src/config.js
src/elements/icon/icon.md

This PR adds support for default config so we can use custom icons here too.
The flow is the following:
1. Load config from this repo and resolve icons with absolute path
2. Search for config in the project root `(/<project_root>/node_modules/@oacore/design/bin)`
3. Resolve icons in this config
4. Merge configs together

Allow to use own design config in the repo

---

src/elements/forms/addon.jsx
src/elements/forms/control.jsx
src/elements/forms/form.jsx
src/elements/forms/group.jsx
src/elements/forms/label.jsx
src/elements/progress-spinner/progress-spinner.jsx

Fixes:
Warning: forwardRef render functions do not support propTypes or defaultProps. Did you accidentally pass a React component?

Move forwardRef closer to Component

---

src/elements/forms/text-field.jsx
src/elements/icon/icon.jsx
src/elements/icon/icon.md

We are missing alt prop for addon icons in [TextFields](https://github.com/oacore/design/blob/master/src/elements/forms/text-field.jsx#L31-L39). I don't think it makes sense to put there any alt attribute because we use arria-hidden there. If you have a better solution for this problem let me know.

Make alt for Icon optional & allow to pass element as a helper prop for TextField

---

bin/config.js

process.cwd() is not sufficient because we issue build icons command manually (because of next build) and process.cwd() is main project dir not design dir

Fix searchForm param

---

src/elements/forms/text-field.jsx

It is used only in dashboard and it will be removed once we merge https://github.com/oacore/dashboard/pull/437

Remove deprecated labelSrOnly

---

src/modules/select/select.css
src/modules/select/select.jsx
src/modules/select/select.md

If select is pure we show label only when input is not focused instead of hiding it

Change variant pure implementation in select component

---

src/modules/select/select.css

When pure select is empty and and gets unfocused for small time label is shown on the border.
It's because it gets time to remove .focused class from element hence using `:focus-with` pseudo selector.
I decided to keep .focused for compatibility reasons.

Fix select label flickering

---

src/elements/forms/text-field.jsx
src/modules/select/select.jsx
src/modules/select/select.md
src/utils/index.js
src/utils/unique-id.js

This never really worked for SSR applications because different ID is generated on server side than on client side. There are some ways to make it work properly but it looks too complicated. Let the user pass it down.
See more:
https://github.com/facebook/react/issues/5867

Drop generateId support

---

src/foundation/colors.css

1. Introduces a new more powerful and flexible technique of using colours and CSS custom properties. The system requires a lot of changes in the project, the slow adaptation approach is taken to replace the --primary colour.
2. Defines the new colour variables that are inspired by the [Material Baseline Design Kit](https://www.figma.com/community/file/778763161265841481/Material-Baseline-Design-Kit) developed by the Material Design group and provided via Figma Community.
3. Deprecates the current colour system in favour of the new more simple one.
This comes from stale #345. Merging can be either proceed or postponed to the time I test the system.

Update colour system to be more powerful and flexible

---

src/foundation/elevation.css
src/foundation/index.css

Defines elevation variables that are inspired by the [Material Baseline Design Kit](https://www.figma.com/community/file/778763161265841481/Material-Baseline-Design-Kit) developed by the Material Design group and provided via Figma Community.
On top of #353, the same rules apply: can be tested and merged or vice versa.

Add global elevation definitions

---

src/modules/header/styles.css

It was a mistake and it shouldn't be there. It was just a coincidence that the layout matched initially. Firstly the gap was 1rem which is almost similar to the width of the scrollbar
https://github.com/oacore/search/blob/layout-align/modules/search-layout/styles.module.css#L5-L15

Remove gap from calculation
