oacore/design

babel.config.js
package-lock.json
package.json
src/utils/class-names.js
src/utils/index.js

As simple as following
```js
import { classNames } from 'utils'
import iconClasses from './icon.css'
const className = classNames.use('icon').withModule(iconClasses)
```

Add classNames utility

---

.gitignore
package.json
styleguide.config.js

I am afraid I missed something in some config file. @Joozty could you please check?

Change build directory to lib

---

src/elements/index.css
src/elements/index.js
src/elements/label.css
src/elements/label.jsx
src/elements/label.md

Add as simple as possible labels that can be used to highlight OAI in data tables.

Add labels

---

src/elements/app-bar/bar.jsx
src/elements/app-bar/bar.md
src/elements/app-bar/brand.jsx
src/elements/app-bar/index.css
src/elements/app-bar/index.js
src/elements/app-bar/item.jsx
src/elements/app-bar/styles.css
src/elements/index.css
src/foundation/type.css
src/utils/class-names.js

1. Fixes classNames utility, closes #44 
2. Fixes links specificity to have less `!important`s
3. Adds simple AppBar component

Add AppBar

---

src/assets/icons/barcode.svg

It is going to be used for DOIs tab in the dashboard

Add barcode icon

---

package.json

This allows us to develop design and dashboard in parallel. There is one caveat that the assets folder needs to be always copied manually.
I tried HRM in the dashboard and it worked like a charm.

Enable watch mode

---

src/elements/card/card.css
src/elements/card/card.jsx
src/elements/card/card.md
src/elements/card/index.js
src/elements/index.css

Add Card Component

---

src/elements/forms/text-field.css
src/elements/forms/text-field.md

Closes https://github.com/oacore/design/issues/178

Style disabled TextFields

---

src/elements/forms/forms.md
src/elements/forms/group.jsx
src/elements/forms/styles.css

It'a simple wrapper around the `<p>` element that adds another class. It will be richer in the future.

Add the FormGroup component

---

src/elements/forms/styles.css
src/elements/forms/text-field.css
src/elements/forms/text-field.jsx

It works but poorly. I guess I lost placeholder placing for the labelSrOnly inputs but it's fine for now.
It's better to have it unified and fix the bug later.

Replace TextField internals with Form-components

---

src/elements/forms/addon.jsx
src/elements/forms/forms.md
src/elements/forms/styles.css
src/elements/forms/text-field.css

I am struggling to make the extra text transparent when the label is shown at the moment.

Develop InputAddon component

---

design.config.js
src/elements/forms/addon.jsx
src/elements/forms/control.jsx
src/elements/forms/form.jsx
src/elements/forms/forms.md
src/elements/forms/group.jsx
src/elements/forms/index.css
src/elements/forms/index.js
src/elements/forms/label.jsx
src/elements/forms/styles.css
src/elements/forms/text-field.css
src/elements/forms/text-field.jsx
src/elements/forms/text-field.md
src/elements/icon/icon.css

This should include:
and some other components for icons, statuses

Develop more flexible form components

---

src/elements/forms/forms.md
styleguide.config.js

Closes https://github.com/oacore/design/issues/210

Form section

---

src/elements/message/message.css
src/elements/message/message.jsx
src/elements/message/message.md

I would like to use fill variant in form messages on [secure pages](https://dashboard.core.ac.uk/login?reason=logout). Not sure about the colours though.

Add fill option to Message component

---

src/elements/forms/addon.jsx
src/elements/forms/control.jsx
src/elements/forms/group.jsx
src/elements/forms/label.jsx

Sorry, I forgot about it. It was very important. Adding it instead #230

Fix missing ref forwarding in form components

---

babel.config.js
package-lock.json
package.json

This helps to debug errors in production build and also helps to distinguish children by type,e.g. `children.type.displayName = 'SelectOption'`

Add automatically displayName to functional components

---

package-lock.json
package.json
src/modules/index.css
src/modules/index.js
src/modules/popover/index.js
src/modules/popover/popover.css
src/modules/popover/popover.jsx
src/modules/popover/popover.md

Closes https://github.com/oacore/design/issues/290

Add Popover component

---

src/index.css
src/reboot.css

The user may easily import just this reboot file and typography. Useful for migrations (@oacore/next)

Move sanitize css to extra file

---

src/modules/select/select.jsx

Prevent the select being submitted when clicked clear button inside the form

Disable default submit action for addon button

---

src/modules/select/hooks/use-options.js
src/modules/select/option.jsx
src/modules/select/select.md

Allows to use this kind of syntax:
```
const booleanValue = false
<Select>
{booleanValue && <Select.Option />}
</Select>
```

Filter Select children

---

src/modules/select/hooks/use-input.js
src/modules/select/hooks/use-options.js
src/modules/select/select.jsx
src/modules/select/select.md

If set to false the onChange is not called on blur event

Add prop changeOnBlur

---

src/modules/modal/modal.jsx

Custom validity function has te return either null or throw an error

Fix prop validation

---

package-lock.json
package.json
src/elements/button/button.css
src/elements/card/card.css
src/elements/detail-list/detail-list.css
src/elements/forms/styles.css
src/elements/forms/text-field.css
src/elements/label.css
src/elements/link/link.css
src/elements/loading-bar/loading-bar.css
src/elements/logo/logo.css
src/elements/table/styles.css
src/foundation/type.css
src/modules/modal/modal.css
src/modules/select/select.css

Drops Prettier support in the Stylelint.
Updates CSS files after rule changes in the stylelint config.

Bump @oacore/stylelint-config-base to 2.0.0-stylelint.1

---

src/foundation/README.md
src/foundation/index.css
src/foundation/loading.css

Currently in the state of experiment. However, I think this will become production-ready very soon ✨

Out-of-the-box loading states 🧪

---

src/foundation/loading.css
src/modules/index.css
src/modules/index.js
src/modules/search-result/author.css
src/modules/search-result/author.jsx
src/modules/search-result/index.css
src/modules/search-result/index.js
src/modules/search-result/metadata.css
src/modules/search-result/metadata.jsx
src/modules/search-result/search-result.jsx
src/modules/search-result/search-result.md
src/modules/search-result/styles.css
styleguide.config.js

The API is more or less good but the feedback would be appreciated 🙂
1. Loading state after #349 
1. Better name for the component?
2. Proper structuring?

SearchResult component

---

src/modules/search-result/author.css
src/modules/search-result/author.jsx
src/modules/search-result/metadata.css
src/modules/search-result/search-result.jsx
src/modules/search-result/search-result.md

Video with screen reader enabled
https://www.loom.com/share/d1d39f8703814893a15d43c489197cd5

More authors

---

src/modules/search-result/search-result.jsx

Maybe it's just me. It looks to me that loading multiple images is slow. Maybe this could help our servers?

Load result images lazily

---

.github/workflows/publish-package.yml

https://github.com/oacore/design/actions/runs/379216231

Replace deprecated command

---

src/modules/header/styles.css

Fix for https://github.com/oacore/search/pull/166#issuecomment-744512873

Fix the menu look and search bar right margin

---

src/modules/search-result/search-result.jsx
src/modules/search-result/search-result.md
src/modules/search-result/styles.css

Also fixes microdata errors.
Note: It's quite important to put span to link otherwise microdata are not recognised correctly.
Tested here https://search.google.com/structured-data/testing-tool

Add publisher name

---

.gitignore
src/elements/link/link.jsx

docs:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLAreaElement/referrerPolicy
https://reactjs.org/docs/dom-elements.html#all-supported-html-attributes

Fix DOM property: hrefLang, referrerPolicy

---

src/modules/select/select.jsx

Revert "Fix select autocomplete"

---

src/elements/logo/data-provider.jsx
src/modules/header/header.jsx
src/modules/header/styles.css

[CORE-4421](https://kmi-ou.atlassian.net/jira/software/c/projects/CORE/boards/5?modal=detail&selectedIssue=CORE-4421&assignee=63722bd63c26ca7fa0d060ae)

CORE-4421 communities dropdow

---

assets/activeArrow.svg
package-lock.json
package.json
src/elements/documentation/documentation.css
src/elements/documentation/documentation.jsx
src/elements/documentationNav/documentationNav.css
src/elements/documentationNav/documentationNav.jsx

[CORE-4461](https://kmi-ou.atlassian.net/jira/software/c/projects/CORE/boards/5?modal=detail&selectedIssue=CORE-4461&assignee=63722bd63c26ca7fa0d060ae)
[CORE-4461]: https://kmi-ou.atlassian.net/browse/CORE-4461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CORE-4461 documentation component

---

src/modules/documentation-membership-nav/documentation-membership-nav.jsx

CORE-4461: add active state on redirect

CORE-4461: add active state on redirect

---

src/elements/footer/footer.jsx

[CORE-4485](https://kmi-ou.atlassian.net/jira/software/c/projects/CORE/boards/5/backlog?view=detail&selectedIssue=CORE-4485&issueLimit=100&assignee=63722bd63c26ca7fa0d060ae)
[CORE-4485]: https://kmi-ou.atlassian.net/browse/CORE-4485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add spacing
